version: '3'
volumes:
  my-db:
services:
  # MySQL
  mysql:
    ports:
      - "3306:3306"
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
      MYSQL_ROOT_PASSWORD: testpassword
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: opentelemetry-tests
    volumes:
      - my-db:/var/lib/mysql

  # REDIS
  redis:
    image: redis
    ports:
      - '6379:6379'
  
  # Collector
  collector:
    image: otel/opentelemetry-collector-contrib:0.53.0
#    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/conf/collector-config.yaml"]
    volumes:
      - ./collector-config.yaml:/conf/collector-config.yaml
    ports:
      - "9464:9464"
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - zipkin-all-in-one

  # Zipkin
  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"

  # Prometheus
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"